### ISSUE TITLE
Feature Request: Make software optional

### ISSUE THREAD

**Issue by timmit99** [SalamiSimon/Easy3DPrint#1]
I'd love to see an "Enable /Disable' checkbox in the settings. I use Cura and Prusa slicer but not AnkerMake/Bambu/Slic3r so having those buttons aren't necessary. Adding an "Enable" button to the settings page for each one and only showing the button if its enabled would be a good feature!
![image](https://github.com/SalamiSimon/Easy3DPrint/assets/8399317/0cba82e8-201f-4b9f-adef-c63aa37642a6)

Thanks for the great software!

Also, unsure if this is feasible, but if the software is open it would be cool if it would just open the new STL/OBJ/3MF i the existing window.

**Comment by timmit99** [comment]
Looking back into this, is it possible to have the disabled slicers not show up in the titlebar?

Instead of this:

<img width="634" height="186" alt="Image" src="https://github.com/user-attachments/assets/517897f9-6d55-4e46-960b-eb6132382d02" />

It would end up like this:

<img width="634" height="186" alt="Image" src="https://github.com/user-attachments/assets/0b75dc60-db5a-4ce2-99ee-bad010e5a3d5" />

**Comment by SalamiSimon** [comment]
I've previously attempted this but was not able to figure out how to hide disabled slicers.

You can hide slicers or buttons you don't use by going to Tools>Easy3DPrint>Customize Menu
