### ISSUE TITLE
One Cura instance for all parts

### ISSUE THREAD

**Issue by Max-GH1** [SalamiSimon/Easy3DPrint#5]
Hello, I don't think this is an issue, but don't know where to write it, sorry.
When I'm preparing a printing bed I want several STL parts in one Cura window. I wonder if could be possible to add a setting to your plugin to choose when to open a new Cura window or add the new part to the existing opened window when pressing the "Open in Cura" button.
Thanks.

**Comment by SalamiSimon** [comment]
That's a limitation in Cura itself, it's possible but very hard to implement. 

You can create an assembly in SW with all the different parts you want to print and then all parts in the assembly will appear in the same Cura project. 

You can then edit an individual parts, update and save the assembly then reload the Cura project.

**Comment by Max-GH1** [comment]
Ohh I get it. Thanks for answering. At least I've discovered you can copy/paste parts between Cura instances.
Your plugin is awesome.
